### ISSUE TITLE
各类框架/库使用过程中的问题和其它

### ISSUE THREAD

**Issue by creeperyang** [creeperyang/blog#20]

**Comment by creeperyang** [comment]
### 1. Koa之`context.is`

```js
app.use((ctx, next) => {
    if (ctx.is('html')) {
    // do something
    }
});

// assume browser opens `localhost:3000/`
```

`context.is`跟我们期待的行为很不一样。我们以为~~只要`content-type`符合，那么这个方法就要返回正确的type~~。 **Naive!!!**

`context.is`的内部实现是`jshttp/type-is`这个库，查看源码可知：

```js
function typeofrequest(req, types_) {
  var types = types_

  // no body
  if (!hasbody(req)) {
    return null
  }
```

在代码检查`content-type`前，已经因为request没有body被打断了。更明确一点，**所有的`GET`请求`context.is`一律返回`null`**。

呵呵...

为什么这么处理？查到的一个比较官方的解释是 https://github.com/koajs/koa/issues/440

**Comment by creeperyang** [comment]
### 2. `path.dirname`在windows平台的行为

```js
path.dirname('/foo/bar/baz/asdf/quux')
// returns '/foo/bar/baz/asdf'
```

unix/linux/osx下，上面代码的执行结果都是一致的。由于windows的盘符概念，`path.dirname`返回的结果需要**特别注意：**

```js
path.dirname('D:\mydir\subdir\index.html')
// returns 'D:'
```

哎...就是这个，我写出了windows下的bug代码...不能说这个返回结果不对，但真的**不符合预期**。

**Comment by creeperyang** [comment]
### 3. windows上`0.0.0.0:3000`无法访问

nodejs server跑在`0.0.0.0`，让同事本机部署时，`0.0.0.0:3000`竟然无法访问，报错**`ERR_ADDRESS_INVALID`**。

解决：

原来windows上`0.0.0.0`被当作无效/未知的域名，服务器跑在`0.0.0.0:3000`后，其实可以

- 本地用`localhost:3000`访问
- 外部用`ip:3000`访问

**Comment by creeperyang** [comment]
### 4. html中的`&#65279;`是什么鬼？？

工作中需要分割项目，从原来代码中拷贝了页面到新仓库，浏览器中浏览页面，Elements面板发现head中的内容漏到body里了，然后body内第一个字符就是`&#65279;`!!

**Comment by creeperyang** [comment]
### 5. shebang line(`#!`) 与node.js工具

写脚本已经是node.js的一个主流功能，比如`gulp-cli`, `webpack-cli`等等。今天用一个小工具突然报了一个莫名其妙的错误，错误原因比较有意思，这里记录下。

```bash
#!/usr/bin/env node

var xxx...
```

一般情况下，脚本都是上面的格式，表示用node去执行下面的js代码。其中第一行叫shebang line，指明用来执行脚本的解释程序。

而使用的小工具报了这样的错误信息：

```bash
env: node\r: No such file or directory
```

❓❓❓

一番排查，问题出在shebang line：

```js
fs.readFileSync('脚本所在路径').toString().slice(0, 30)

// --->

'#!/usr/bin/env node\n\n\'use stri'  // 正常的
'#!/usr/bin/env node\r\n\r\n\'use st' // 报错的
```

是不是看出什么了？对的，问题就出在`\r`上。

unix/linux 下，换行符是`\n`，于是，有问题的shebang line被解析后，env是`node\r`，而不是`node`。所以系统根本没法找到一个叫`node\r`的程序来执行这段脚本...

最后问了工具的开发者，他在windows上开发，😭 😭 ， 这就是`\r\n`哪里来的....

**Comment by creeperyang** [comment]
---

**分割线** 下面将按分类组织

---

**Comment by creeperyang** [comment]
# Node.js 相关

### socket 之 `ECONNRESET`

#### 资料

1. [http.Agent: idle sockets throw unhandled ECONNRESET](https://github.com/nodejs/node/issues/3595)

**Comment by creeperyang** [comment]
### 7. Chrome中请求`canceled`问题

问题描述：

![image](https://cloud.githubusercontent.com/assets/8046480/21187633/a12d59de-c253-11e6-9c18-71dcf82355ac.png)

**Comment by creeperyang** [comment]
### 8. `git hook` 未执行的一个可能原因

1. 某个库，开发时watch代码并实时编译。
2. 然后内部有个服务器会同步库所在的repo，并需要用网页展示该库的文档（依赖编译后的资源）。

服务器上直接watch仓库内代码可能会有性能问题，那么，在服务器上的repo直接写个`post-merge`的本地hook更合适——每当代码同步后跑编译命令（包括build出文档）。

然后碰到一个问题：`.git/hooks/post-merge`这个hook就是不执行，包括试过直接`git pull`而不是用已有的`webhook API`同步，包括把hook脚本改为最简单的`echo`——就是没反应。

想了又想，会不会是权限问题？

```bash
ls -al .git/hooks

# post-merge 果然和其它的妖艳贱货不一样 😂 

chmod -R 777 .git/hooks/post-merge
```

然后再测试，果然可以了....

**Comment by kkshaq** [comment]
hi，你好。请教一下ECONNRESET的问题，按理说如果收到RST报文之后去read，就会报ECONNRESET的错误，那么在node中是怎么处理的？
我如果想catch到这个error，是否用.on('error‘,callback)去监听？你说的有些版本这个错误是silent的，有些则直接抛出是什么意思？能否更详细的解释一下。
我试过server 发送rst给client，client那边用.on('error‘’，callback）去监听，但是并不能catch到error，
只能catch到ECONNREFUSED之类的错误。
谢谢！

**Comment by creeperyang** [comment]
@kkshaq silent是指这个错误不会向上抛出，比如uncaughtException不能捕获到这个错误。另外，http上是捕获不到这个错误的，必须在socket上监听。

**Comment by creeperyang** [comment]
### 9. socket 之 `ECONNABORTED`

收到这样一个错误截图：

![error](https://cloud.githubusercontent.com/assets/8046480/24185207/cd8d0bfe-0f0c-11e7-9b2c-e1359f9fad31.png)

没有什么思路，看起来应该又是一个socket相关的错误，于是查相关资料。

`ECONNABORTED`错误的含义是 `"software caused connection abort"`，看起来就是连接被意外关闭导致的错误。然后看到下面一段解释：

> 考虑这种情况： *TCP连接被客户端夭折，即在服务器调用accept之前，客户端主动发送RST终止连接，导致刚刚建立的连接从就绪队列中移出* ，如果套接口被设置成阻塞模式，服务器就会一直阻塞在accept调用上，直到其他某个客户建立一个新的连接为止。但是在此期间，服务器单纯地阻塞在accept调用上，就绪队列中的其他描述符都得不到处理。

> 解决办法是把监听套接口设置为非阻塞，当客户在服务器调用accept之前中止某个连接时，accept调用可以立即返回-1，这时源自Berkeley的实现会在内核中处理该事件，并不会将该事件通知给epool，而其他实现把errno设置为**ECONNABORTED**或者EPROTO错误，我们应该**忽略**这两个错误。

看起来比较可信的解释（符合我所遇到的情况）是socket刚建立，客户端立即发送了RST；而这个错误看起来可以忽略？

---

**资料：**

1. [Epoll在LT和ET模式下的读写方式](http://ju.outofmemory.cn/entry/35478)
2. [libuv源码分析](https://github.com/paulran/libuv-source-analysis)
3. [What does ECONNABORTED mean when trying to connect a socket?](http://stackoverflow.com/questions/9646550/what-does-econnaborted-mean-when-trying-to-connect-a-socket)

**Comment by creeperyang** [comment]
### 10. 怎么处理 unhandled Promise rejections ？

如图所示，程序忽略 Promise rejections 继续处理过程，但是console里输出了相应信息。

**Comment by creeperyang** [comment]
### 11. `https.get/request` 请求 self-signed 的 https 服务器的失败问题。

leader想做个内部工具，需要接入公司的`cas`系统做用户登陆验证，内部文档提供的示例并不包括`node.js`。

1. 摸索了几十分钟，用`connect-cas`搭配`express.js`做个demo，总是显示`unauthorized`，看起来就像验证未通过，但跳转登陆的页面却没有显示（这种情况应该是已经登陆了）。
2. 换用`node-cas`，检索源码，发现`https.get`有个`rejectUnauthorized`的配置。联想到公司内网都是自签名证书，于是明白，应该是证书校验没通过，直接失败了。果然，设置为`false`后成功拿到了用户信息。

> `rejectUnauthorized` <boolean> If true the server will reject any connection which is not authorized with the list of supplied CAs. This option only has an effect if requestCert is true. Defaults to false.

**Comment by creeperyang** [comment]
### 12. `child_process.exec`之`Error: stdout maxBuffer exceeded`

最近为交互部门写的axure文档预览工具，需要从 gitlab 同步仓库。发现有时交互们提交文档后服务器的目录列表没有同步。

查看错误日志：

```bash
{ Error: stdout maxBuffer exceeded
     at Socket.<anonymous> (child_process.js:255:14)
     at emitOne (events.js:96:13)
     at Socket.emit (events.js:188:7)
     at readableAddChunk (_stream_readable.js:172:18)
     at Socket.Readable.push (_stream_readable.js:130:10)
     at Pipe.onread (net.js:542:20)
   cmd: 'cd /root/projects/UXD/lt && git reset HEAD --hard && git pull origin master' }
```

搜索后可知：`child_process.exec` 默认的 `maxBuffer` 是 **200KB** ，而交互们提交文档的改动可能比我们想象的大多了，修改 `maxBuffer` 后解决问题。

**Comment by creeperyang** [comment]
### 13. `The header content contains invalid characters`

**Comment by creeperyang** [comment]
### typescript 对 `umd` 的支持问题

详情见 https://github.com/Microsoft/TypeScript/issues/8436

一句话，`"module": "umd"` 时，编译后的代码里，`umd` 只有 `commonjs` 和 `amd` 的兼容代码，并没有最后的 fallback：挂载到全局对象。

**Comment by creeperyang** [comment]
### 15. npm 的 `dependencies` vs `peerDependencies`

`dependencies`很好理解，就是字面意思的依赖，一般会通过`require`在代码中引入使用；它是一种实现细节，是 **"private"** 的，即不会暴露给使用者。

相反，`peerDependencies`是主动暴露给使用者知晓的，并且，一般情况下使用者也被预期会（需要）使用这些`peerDependencies`。

下面以库 A 作为例子来解释：

比如你要写一个库 A，你想使用 `lodash` 提供的一些工具函数，那么，你会把`lodash` 加到 `dependencies`中（作为依赖）。但是，别人使用你的库 A 时，是不（用）知道你依赖了`lodash`的，因为这是一种实现细节，只要`npm`自动帮你安装`lodash`即可（A可以正常运行）。

但是，当你想写当库 A 是一个插件（比如 webpack 插件，或者 react 组件，或者其它类似），A 需要依赖某个框架 K 才能正常工作，通常情况下，（库 A）的使用者也会同时使用框架 K。这通常也没什么大问题，但是如果你依赖 `K@v2` 而使用者用了 `K@v1`，这可能会**不兼容**！所以，你需要通过一种方式告诉 A 的使用者，A 依赖`K@v2` 才能正常工作，这就是`peerDependencies`的作用。

在`npm@3`之前，[`peerDependencies`](https://docs.npmjs.com/files/package.json#peerdependencies)会被自动安装，但从3开始不会自动安装，只会输出警告信息。

**Comment by creeperyang** [comment]
### 16. `eslint-scope@3.7.2` 的一个安全问题以及提高警惕

事件：`eslint-scope@3.7.2`的`postinstall`有一段可疑代码，会把用户本地的`.npmrc` 上传到远程服务器，即偷取token。

详情：**[Virus in eslint-scope?](https://github.com/eslint/eslint-scope/issues/39#issuecomment-404533026)**。

结论：这个版本并不是官方团队所发布，很可能`eslint`团队的发布token被盗了... 目前该版本已被撤除，但值得大家警惕。

**Comment by creeperyang** [comment]
### 17. git 快捷命令一览

- 怎么查看stash中文件有哪些变化？

    `git stash show -p stash@\{0\}`

**Comment by creeperyang** [comment]
### 18. unix-like 系统的文件权限
![image](https://user-images.githubusercontent.com/8046480/53465308-5b1b7480-3a88-11e9-846c-71b6558d91f8.png)

**Comment by creeperyang** [comment]
### 19. windows 安装某些 native 包时报错 `...\.node-gyp\10.12.0\x64\node.lib : fatal error LNK1127: 库已损坏`

解决方案：替换 `node.lib`。

去官网下载对应版本的 `node.lib`，比如我们这里是 `https://nodejs.org/download/release/v10.12.0/win-x64/node.lib`，替换`C:\Users\name\.node-gyp\10.12.0\x64\node.lib`即可。

**Comment by creeperyang** [comment]
### 20. windows 上查看端口占用和杀进程

查看 3000 端口占用，并显示 PID
```bash
# https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/netstat
netstat -ano | findstr "3000"
```

强行终止进程6620
```bash
taskkill -PID 6620 -F
```

**Comment by creeperyang** [comment]
### 21. semver 版本控制规范的问题

**`[major, minor, patch]`**

#### Tilde Ranges ~1.2.3 ~1.2 ~1

波浪线（~），允许更新指定版本（位数）的**后一位**。

- 指定一位，允许更新第2位和第3位，`~1` --> >=1.0.0 <2.0.0；
- 指定2位，允许更新第3位，`~1.2` --> >=1.2.0 <1.3.0；
- 指定3位，允许更新第3位，`~1.2.3` --> >=1.2.3 <1.3.0。

#### Caret Ranges ^1.2.3 ^0.2.5 ^0.0.4

Caret（^），允许**不修改从左开始的第一位非零位**的变动。

- 对 `^1.2.3` --> >=1.0.0 <2.0.0；
- 对 `^0.2.3` --> >=0.2.3 <0.3.0；
- 对 `^0.0.3` --> >=0.0.3 <0.0.4；

**Comment by creeperyang** [comment]
### 21. React hydrate() 的问题

对服务器端渲染，我们通常要在客户端使用 hydrate() 复用SSR结果，并去处理事件绑定等。在实际使用时，碰到一个问题：客户端渲染得到的DOM有问题，元素的class/style和预期不一致。

查找原因后发现，问题出在服务端渲染和客户端渲染得到的VDOM tree不一致，而这个在hydrate()的使用中被视为bug。

- https://github.com/facebook/react/issues/11336
- https://github.com/reactjs/reactjs.org/pull/200

**Comment by creeperyang** [comment]
### 22. localStorage 存满导致的问题

查一个线上问题，感觉代码没任何问题：

```js
function run() {
doA(); // 理解为当且仅当全局变量 GGG 没值时提示操作
localStorage.setItem('key', value);
doB();  // 理解为设置GGG的值（当且仅当该变量GGG未赋值时设置值）
}
```

上面的 `run` 多次执行时反复提示操作，开始觉得代码没任何问题。排除所有的可能后，唯一的不可能就是可能：`localStorage.setItem` 出错了，导致 `doB` 没执行。

- 可能浏览器隐私模式导致报错？测试后发现不是；
- 最后得出  localStorage 达到容量上限，直接报错了，一查，果然有极少量 `setitem exceeded the quota` 报错。

**Comment by creeperyang** [comment]
### 23. `Error: ES Modules may not assign module.exports or exports.*, Use ESM export syntax`

babel 的报错，解决办法：代码中不要混用`import/export` 和 `require/module.exports`。

**Comment by 18boys** [comment]
已收到,稍候会处理best wish~

**Comment by creeperyang** [comment]
### 24. webpack@5 和 @babel@7 的问题

```bash
For the selected environment is no default script chunk format available:
JSONP Array push can be chosen when 'document' or 'importScripts' is available.
CommonJs exports can be chosen when 'require' or node builtins are available.
```

![image](https://user-images.githubusercontent.com/8046480/219876670-c75a84e5-230d-468a-820a-acd013a84f39.png)

![image](https://user-images.githubusercontent.com/8046480/219876717-e2cadda3-b649-4853-984f-271733580b01.png)
删除browserslist 中node相关配置即可，从错误来看，node和browser都配置，会让webpack无法确定默认的`script chunk format`。
